---
version: '3.3'

services:
    web:
        image: nginx:latest
        ports:
            - "8181:80"
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php 
        networks:
            - code-network
    php:
        image: php-project:latest 
        volumes:
            - ./public:/var/www/public
        depends_on:
            - db      
        networks:
            - code-network
    db:
       image: mysql
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root
       ports:  
            - "3307:3306" 
       networks:
            - code-network
    composer: 
             container_name: composer
             image: composer:1.6.5
             volumes:
                 - /home/edureka/php-project:/app
             command: ["composer", "update"]
             command: ["composer", "install"]
             networks:
                   - code-network 
    php-testing:
               container_name: php-testing
               image: phpunit/phpunit:6.5.3
               volumes:
                   - ./tests/unit:/app
               command: ["phpunit -c tests/unit/phpunit.xml tests/unit"]
               networks:
                     - code-network
            
networks:
    code-network:
        driver: bridge
