---
version: '3.3'

services:
    web:
        image: nginx:latest
        ports:
            - "8181:80"
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db
        networks:
            - code-network
    php:
        image: php-frame:latest 
        volumes:
            - ./public:/var/www/public
        networks:
            - code-network
    db:
       image: mysql
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root
       networks:
            - code-network
     
networks:
    code-network:
        driver: bridge
